#!/usr/bin/env python3
"""Materialize a box clip's labels as a <clip>.labels.yaml sidecar.

Runs the same box-height rule the loader falls back to and writes its
output -- with the rule's internals as comments -- so hand-tuning starts
from what the rule actually decided. The loader then prefers the sidecar,
and its content is fingerprinted into the cache (edits rebuild it).

    python tools/make_labels.py sub12_largebox_001 [...]
    python tools/make_labels.py --all
    (add --force to overwrite existing sidecars)
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from mm_g1 import config as C
from mm_g1 import boxes, labels
from mm_g1.data import _box_clip_names, _load_box_npz


def make_one(stem, force=False):
    path = labels.sidecar_path(C.BOX_DATA_DIR, stem)
    if os.path.exists(path) and not force:
        print(f"skip  {os.path.basename(path)} (exists; --force to overwrite)")
        return
    _, box_pose = _load_box_npz(stem)
    T = len(box_pose)
    _, attach, info = boxes.segment_phases(box_pose[:, 0:3])
    on = attach.nonzero()[0]
    span = [[int(on[0]), int(on[-1]) + 1]] if len(on) else []
    with open(path, "w") as f:
        f.write(f"""\
# Labels for {stem} ({T} frames @ {C.FPS} fps). Generated by
# tools/make_labels.py from the box-height rule; tune freely -- the loader
# prefers this file, and edits rebuild the cache automatically.
# Rule internals: box rest z {info['z_rest']:.3f} m, peak {info['z_peak']:.3f} m;
# carry = above rest + {C.BOX_CARRY_FRAC} * (peak - rest); held = lifted
# > {C.BOX_HOLD_DZ} m or moving > {C.BOX_HOLD_SPEED} m/s, collapsed to one span.
# Spans are half-open [start, stop) frame ranges.
phases:
  pick:  [{info['pick'][0]}, {info['pick'][1]}]
  carry: [{info['carry'][0]}, {info['carry'][1]}]
  place: [{info['place'][0]}, {info['place'][1]}]
contact:            # per-hand; attach is derived as their union span
  left_hand:  {span}
  right_hand: {span}
""")
    print(f"wrote {os.path.basename(path)}  phases "
          f"pick {info['pick']} carry {info['carry']} place {info['place']}, "
          f"contact {span}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("stems", nargs="*", help="clip stems (in data/robot_object_g1)")
    ap.add_argument("--all", action="store_true", help="every loadable box clip")
    ap.add_argument("--force", action="store_true", help="overwrite existing sidecars")
    args = ap.parse_args()
    stems = _box_clip_names() if args.all else args.stems
    if not stems:
        ap.error("give clip stems or --all")
    for stem in stems:
        make_one(stem, force=args.force)


if __name__ == "__main__":
    main()
